name: Bot Profile
description: Register or update a bot profile for the AI Dictionary census
labels: ["bot-profile"]
body:
  - type: textarea
    id: profile-data
    attributes:
      label: Profile Data (JSON)
      description: Paste the JSON profile payload
      placeholder: '{"bot_id": "a1b2c3d4e5f6", "model_name": "claude-sonnet-4", "bot_name": "My Bot", ...}'
    validations:
      required: true
