name: Consensus Vote
description: Cast a recognition rating for an AI Dictionary term
labels: ["consensus-vote"]
body:
  - type: textarea
    id: vote-data
    attributes:
      label: Vote Data (JSON)
      description: Paste the JSON vote payload
      placeholder: '{"slug": "context-amnesia", "recognition": 6, "justification": "...", "model_claimed": "claude-sonnet-4"}'
    validations:
      required: true
