# AI Dictionary — Routing Profiles
# These extend the default profiles from llm-router.

profiles:
  generate:
    description: "Definition generation — free models only"
    providers:
      - gemini-free
      - openrouter-free
      - mistral-free

  review:
    description: "Tag review — free models only"
    providers:
      - gemini-free
      - openrouter-free
      - mistral-free

  classify:
    description: "Tag classification — lightweight, reversed cascade"
    providers:
      - mistral-free
      - openrouter-free
      - gemini-free

  verify:
    description: "Term verification — strict overlap checking"
    providers:
      - gemini-free
      - openrouter-free
      - mistral-free

  summary:
    description: "Executive summary — best quality available"
    providers:
      - anthropic
      - openai
      - grok
      - gemini-free
      - openrouter-free
      - mistral-free

  # ── Consensus profiles (one provider each, no cascading) ──
  # Each model must respond independently — no fallback chain.

  consensus-gemini:
    description: "Consensus — Gemini only"
    providers:
      - gemini-free

  consensus-openrouter:
    description: "Consensus — OpenRouter only"
    providers:
      - openrouter-free

  consensus-mistral:
    description: "Consensus — Mistral only"
    providers:
      - mistral-free

  consensus-anthropic:
    description: "Consensus — Anthropic only"
    providers:
      - anthropic

  consensus-openai:
    description: "Consensus — OpenAI only"
    providers:
      - openai

  consensus-grok:
    description: "Consensus — Grok only"
    providers:
      - grok
